layout: {qmk_keyboard: corne_rotated, qmk_layout: LAYOUT_split_3x6_3}
layers:
  default: [TAB, Q, W, E, R, T, Y, U, I, O, P, BSPC, LCTRL, A, S, D, F, G, H, J, K, L, ;, '''', LSHFT, Z, X, C, V, B, N, M, ',', ., /, ESC, LGUI, lower, SPACE, RET,
    raise, LEFT ALT]
  lower:
  - TAB
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - BSPC
  - LCTRL
  - {t: BT, h: '0'}
  - {t: BT, h: '1'}
  - {t: BT, h: '2'}
  - {t: BT, h: '3'}
  - OUT TOG
  - LEFT
  - DOWN
  - UP
  - RIGHT
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - LSHFT
  - {t: BT DISC, h: '0'}
  - {t: BT DISC, h: '1'}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - BT CLR
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - LGUI
  - {type: held}
  - SPACE
  - RET
  - {t: ▽, type: trans}
  - LEFT ALT
  raise:
  - TAB
  - '!'
  - '@'
  - '#'
  - $
  - '%'
  - ^
  - '&'
  - KP MULTIPLY
  - (
  - )
  - BSPC
  - LCTRL
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - '-'
  - '='
  - '['
  - ']'
  - \
  - '`'
  - LSHFT
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - _
  - +
  - '{'
  - '}'
  - '|'
  - '~'
  - LGUI
  - {t: ▽, type: trans}
  - SPACE
  - RET
  - {type: held}
  - LEFT ALT
  double:
  - F1
  - F2
  - F3
  - F4
  - F5
  - F6
  - F7
  - F8
  - F9
  - F10
  - F11
  - F12
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - Ctl+Gui+ LEFT
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - Ctl+Gui+ RIGHT
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - HOME
  - END
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {t: ▽, type: trans}
